/**
 * The single way this app talks to FastAPI (Phase 3 spec §3).
 *
 * Types come from `schema.d.ts`, generated by openapi-typescript from the
 * committed `openapi.json` (`npm run types:api`). CI fails when that file
 * drifts from the routes, so a backend change that breaks a screen breaks the
 * build first.
 *
 * The generated file is *not* named api.d.ts: TypeScript resolves `./api` to
 * api.ts and would shadow it entirely, leaving every response silently typed
 * `any` while the app still ran.
 *
 * Runtime behaviour is hand-written rather than generated: base URL, attaching
 * the session token, and turning a non-2xx into a typed error instead of a
 * rejected promise with an unhelpful message.
 */
import "server-only";

import { API_BASE_URL } from "./config";
import type { paths } from "./schema";

/** Every path FastAPI serves, as a string union. */
export type ApiPath = keyof paths;

export class ApiError extends Error {
  constructor(
    readonly status: number,
    readonly detail: string,
    readonly path: string,
  ) {
    super(`${status} ${path}: ${detail}`);
    this.name = "ApiError";
  }

  /** The demo account hitting a write route. Screens render this, not a crash. */
  get isReadOnly(): boolean {
    return this.status === 403;
  }

  get isNotFound(): boolean {
    return this.status === 404;
  }
}

type FetchOptions = Omit<RequestInit, "body"> & {
  /** Serialized as JSON unless it is already a string or FormData. */
  body?: unknown;
  /** Appended as a query string; null and undefined entries are dropped. */
  query?: Record<string, string | number | boolean | null | undefined>;
  /** Bearer token. Server Components read it from the cookie via `session.ts`. */
  token?: string | null;
};

function buildUrl(path: string, query: FetchOptions["query"]): string {
  const url = new URL(API_BASE_URL + path);
  for (const [key, value] of Object.entries(query ?? {})) {
    if (value !== null && value !== undefined && value !== "") {
      url.searchParams.set(key, String(value));
    }
  }
  return url.toString();
}

/**
 * FastAPI's error body is `{detail: ...}`, where detail is a string for
 * HTTPException and an array of validation objects for a 422. Flatten both into
 * one readable line so a screen never renders "[object Object]".
 */
async function extractDetail(response: Response): Promise<string> {
  const text = await response.text();
  if (!text) return response.statusText || "Request failed";

  try {
    const parsed = JSON.parse(text) as { detail?: unknown };
    const detail = parsed.detail;
    if (typeof detail === "string") return detail;
    if (Array.isArray(detail)) {
      return detail
        .map((item) => {
          const e = item as { loc?: unknown[]; msg?: string };
          const where = Array.isArray(e.loc) ? e.loc.join(".") : "";
          return where ? `${where}: ${e.msg ?? "invalid"}` : (e.msg ?? "invalid");
        })
        .join("; ");
    }
    return detail ? JSON.stringify(detail) : text.slice(0, 200);
  } catch {
    return text.slice(0, 200);
  }
}

/**
 * Call the API and return the parsed body.
 *
 * `apiFetch<T>("/api/candidates/")` — the caller supplies the response type,
 * normally via the `Response<...>` helpers below.
 */
export async function apiFetch<T>(
  path: ApiPath | (string & {}),
  { body, query, token, headers, ...init }: FetchOptions = {},
): Promise<T> {
  const isForm = typeof FormData !== "undefined" && body instanceof FormData;
  const requestHeaders = new Headers(headers);

  if (token) requestHeaders.set("Authorization", `Bearer ${token}`);
  if (body !== undefined && !isForm && typeof body !== "string") {
    requestHeaders.set("Content-Type", "application/json");
  }

  let response: Response;
  try {
    response = await fetch(buildUrl(path, query), {
      ...init,
      headers: requestHeaders,
      body:
        body === undefined
          ? undefined
          : isForm || typeof body === "string"
            ? (body as BodyInit)
            : JSON.stringify(body),
      // The API is per-request state, never a build-time constant. Without
      // this, Next would happily cache a candidate list into the static output.
      cache: init.cache ?? "no-store",
    });
  } catch {
    // A refused connection is the single most likely local failure (uvicorn not
    // running). Say so, rather than surfacing a bare "fetch failed".
    throw new ApiError(
      503,
      `Cannot reach the API at ${API_BASE_URL}. Is uvicorn running?`,
      String(path),
    );
  }

  if (!response.ok) {
    // A 401 with a token means the cookie outlived its signing secret (the
    // backend mints a random one per process when JWT_SECRET is unset). Every
    // screen the demo can see also answers anonymously, so behave as signed
    // out rather than stranding the visitor until they clear cookies.
    if (response.status === 401 && token) {
      return apiFetch<T>(path, { body, query, token: null, headers, ...init });
    }
    throw new ApiError(response.status, await extractDetail(response), String(path));
  }

  if (response.status === 204) return undefined as T;
  const text = await response.text();
  return (text ? JSON.parse(text) : undefined) as T;
}

/**
 * `apiFetch` that answers `null` for a 404 instead of throwing.
 *
 * For detail screens, where "no such candidate" is a page state rather than an
 * error. Other statuses still throw.
 */
export async function apiFetchOptional<T>(
  path: ApiPath | (string & {}),
  options: FetchOptions = {},
): Promise<T | null> {
  try {
    return await apiFetch<T>(path, options);
  } catch (error) {
    if (error instanceof ApiError && error.isNotFound) return null;
    throw error;
  }
}

/** Response body type for a GET, straight out of the generated schema. */
export type GetResponse<P extends ApiPath> = paths[P] extends {
  get: { responses: { 200: { content: { "application/json": infer R } } } };
}
  ? R
  : never;

/** Response body type for a POST. */
export type PostResponse<P extends ApiPath> = paths[P] extends {
  post: { responses: { 200: { content: { "application/json": infer R } } } };
}
  ? R
  : never;

/** Shorthand for the generated component schemas. */
export type Schema<K extends keyof Components> = Components[K];
type Components = import("./schema").components["schemas"];
