"""add created_at and updated_at to jobs

Revision ID: 35a0f301dcaf
Revises: 005_cand_skills
Create Date: 2025-04-16 13:26:59.908739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35a0f301dcaf'
down_revision: Union[str, None] = '005_cand_skills'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('uq_candidate_skill', 'candidate_skills', ['candidate_id', 'skill_id'])  # Already exists, so skip
    op.drop_column('candidates', 'skills')
    op.add_column('jobs', sa.Column('job_overview', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('required_qualifications', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('jobs', 'responsibilities')
    op.drop_column('jobs', 'description')
    op.drop_column('jobs', 'requirements')
    op.drop_column('skills', 'skills')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('skills', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('requirements', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('responsibilities', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('jobs', 'updated_at')
    op.drop_column('jobs', 'created_at')
    op.drop_column('jobs', 'required_qualifications')
    op.drop_column('jobs', 'job_overview')
    op.add_column('candidates', sa.Column('skills', sa.TEXT(), autoincrement=False, nullable=True))
    # op.drop_constraint('uq_candidate_skill', 'candidate_skills', type_='unique')  # Already exists, so skip
    # ### end Alembic commands ###
